### ISSUE TITLE
Duplicate lines in english\pr.utxt

### ISSUE THREAD

**Issue by SINE** [realitymod/pr-localization#17]
Line 586 and 587

```
HUD_HUD_SQUAD_ORDER_SENT_MEMBERS                            
HUD_HUD_SQUAD_ORDER_SENT_MEMBERS                            
```

Line 598 and 599

```
HUD_TEXT_COMMANDER_BUILD                                   BUILD
HUD_TEXT_COMMANDER_BUILD                                   BUILD
```

These were the lines that I had previously removed in my pull request commit (https://github.com/SINE/pr-localization/commit/93997d6bdd3dbb00a9d3f10344a0f4aed2c1fc09) but reverted by request.

**Comment by AncientMan2002** [comment]
Thanks, fixed :+1:
