### ISSUE TITLE
Some places/menus doesn't support "Ё" character

### ISSUE THREAD

**Issue by Blueberryy** [realitymod/pr-localization#68]
Main menu seems alright, but kit selection, scoreboard cursor activation hint and radio message menu strings just makes text starting "Ё" invisible.
And i don't think that it's font problem because i'm sure it supports that glyph, so it's more of a font code parameter bug for these places.

**Comment by Blueberryy** [comment]
![PRBF2_FCdELD41c4](https://user-images.githubusercontent.com/36592509/229497264-30871c4a-8e65-4bcc-abef-d021702d72ec.png)
It should be "ОГРАНИЧЕНО - ПУЛЕМЁТЧИК"

**Comment by Blueberryy** [comment]
![image](https://user-images.githubusercontent.com/36592509/229497673-46ae329d-cef5-43ec-ba5f-72187066ad42.png)
It looks okay in Keyboard options menu (shows Ё at category names as it should)

**Comment by WouterJansen** [comment]
Sorry for the late response @Blueberryy. But I believe the issue is not with the accent as the localisation source shows, no accent is used there in the translation. https://github.com/realitymod/pr-localization/blob/master/russian/pr.utxt#L783

So I think maybe that part of the menu has a limited amount of characters it can show there and the line is simply too long?

**Comment by Blueberryy** [comment]
well i guess game font is just a little restricted there and don't show this character

**Comment by Mats391** [comment]
The issue is that the font does not support the Cyrillic E (U0415). It either needs to be added to the font or the localization adjusted to use Latin E (U0045)

**Comment by WouterJansen** [comment]
@Blueberryy, I assume you are getting this error on your own version of the localization where you introduce the Ё here? Cause in our current localization it is just the Cyrillic E as Mats391 says and renders just fine on my end in 1.7.4.3.

![image](https://github.com/realitymod/pr-localization/assets/22573859/96e54177-42a2-4fbb-8cb4-3cf29f680189)

If not and you are having this error currently in game, which version, map, faction was this happening on?

**Comment by Blueberryy** [comment]
> @Blueberryy, I assume you are getting this error on your own version of the localization where you introduce the Ё here? Cause in our current localization it is just the Cyrillic E as Mats391 says and renders just fine on my end in 1.7.4.3.
> 
> ![image](https://github.com/realitymod/pr-localization/assets/22573859/96e54177-42a2-4fbb-8cb4-3cf29f680189)
> 
> If not and you are having this error currently in game, which version, map, faction was this happening on? 
> 

Well i reverted changes due to this bug so yeah i replaced it with regular Е

**Comment by WouterJansen** [comment]
Yeah in that case this is font issue as part of the game, not really a localization issue.  Sorry for the confusion. https://github.com/realitymod/pr-localization?tab=readme-ov-file#custom-fonts
